{
 "title": "Global",
 "tags": [
  "nodes",
  "network",
  "public"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Globals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "query": "SELECT mean(\"clients.total\") AS \"Clients - Total\", mean(\"nodes\") AS \"Nodes\", mean(\"clients.wifi\") AS \"Clients - Wifi\", mean(\"clients.wifi24\") AS \"Clients 2.4 Ghz\", mean(\"clients.wifi5\") AS \"Clients 5 Ghz\" FROM \"global\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "clients.wifi24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients 2.4 Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.wifi5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients 5 Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.wifi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients Wifi" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients Total" ], "type": "alias" }
      ],
      [
       { "params": [ "nodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Nodes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"model\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "firmware",
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "model",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}