- name: Create wireguard configuration
  template:
    src: 'wireguard.j2'
    dest: '/etc/wireguard/wg-nodes.conf'
    mode: 0644
  notify:
    - Reconfigure wg-nodes

- name: Create wireguard interfaces
  template:
    src: 'interface.j2'
    dest: '/etc/network/interfaces.d/wg-nodes'
    mode: 0644
  notify:
    - Activate wg-nodes interface
