- name: Add /etc/network/interfaces.d
  file:
    path: /etc/network/interfaces.d
    state: directory

- name: Create file /etc/network/interfaces
  # required for the lineinfile to work on a fresh Ubuntu 24.04 cloud image
  ansible.builtin.file:
    path: '/etc/network/interfaces'
    access_time: preserve
    state: touch

- name: Set /etc/network/interfaces include path
  # FIXME maybe rename files to *.cfg to avoid this?
  become: true
  lineinfile:
    dest: '/etc/network/interfaces'
    regexp: '^source '
    line: 'source /etc/network/interfaces.d/*'
    state: present
