---
# - name: Disable apt autostart
#   copy:
#     src:  'policy-rc.d'
#     dest: '/usr/sbin/'
#     mode: 0755
# - name: Configure APT default release
#   template:
#     src: "apt.conf.j2"
#     dest: "/etc/apt/apt.conf"
#     owner: "root"
#     group: "root"
#     mode: "0644"
# - name: Configure APT preferences
#   template:
#     src: "preferences.j2"
#     dest: "/etc/apt/preferences"
#     owner: "root"
#     group: "root"
#     mode: "0644"
# - name: Configure APT sources
#   template:
#     src: "sources.list.j2"
#     dest: "/etc/apt/sources.list"
#     owner: "root"
#     group: "root"
#     mode: "0644"
# - name: Install etckeeper package
#   become: true
#   apt: name=etckeeper update_cache=yes state=present
- name: Update apt
  apt:
    update_cache: true
- name: Install standard packages
  become: true
  apt:
    state: present
    name:
      - linux-image-generic
      - rsync
      - htop
      - curl
      - tcpdump
      - mtr
      - strace
      - signify-openbsd
      # - acl
      # - netcat-openbsd
      # - aptitude
      # - locales-all
      # - mc
      # - molly-guard
      # - needrestart
      # - pinentry-curses
      # - qemu-guest-agent
      # - rng-tools
      # - screen
      # - tig
      # - tmux
      # - unattended-upgrades
      # - vim-nox
      # - jq
      # - needrestart
      # - psmisc
      # - dwdiff
      # - dnsutils
      # - iputils-tracepath
# - name: Remove useless packages
#   become: true
#   apt:
#     state: absent
#     purge: yes
#     name:
#       - acpi
#       - acpid
#       - at
#       - debian-faq
#       - dmidecode
#       - eject
#       - ftp
#       - iamerican
#       - ibritish
#       - ispell
#       - laptop-detect
#       - libclass-isa-perl
#       - libswitch-perl
#       - m4
#       - mutt
#       - nano
#       - nfs-common
#       - os-prober
#       - pinentry-gtk2
#       - procmail
#       - rdnssd
#       - rpcbind
#       - telnet
#       - texinfo
#       - vim-tiny
#       - wamerican
#       - xauth
#       - xdg-user-dirs
# - name: Run needrestart in auto mode
#   command: needrestart -r a
